# Generated by Django 2.2.3 on 2019-09-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='x',
            new_name='title',
        ),
    ]
