# Generated by Django 2.2.3 on 2019-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/image/full_size'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(path='static/image/thumb'),
        ),
    ]
